name: progression_problems Testing

on:
  push:
  schedule:
    # Run every day at 8:00 AM UTC (3:00 AM CDT)
    - cron: '0 8 * * *'

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set Up Python and Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.11
        channels: conda-forge

    - name: Set Up and Configure Environment
      run: |
        conda install -n base -y mamba -c conda-forge
        mamba create -n openmc-env -y python=3.11 openmc hdf5 mpi4py numpy scipy pandas -c conda-forge
        source $(conda info --base)/etc/profile.d/conda.sh && conda activate openmc-env
        python -m pip install pylint pytest

    - name: Install MPACTPy from Repo
      run: |
        source $(conda info --base)/etc/profile.d/conda.sh && conda activate openmc-env
        cd /tmp
        git clone https://github.com/UT-Computational-NE/MPACTPy.git
        cd MPACTPy
        python -m pip install .

    - name: Install CoreForge from Repo
      run: |
        source $(conda info --base)/etc/profile.d/conda.sh && conda activate openmc-env
        cd /tmp
        git clone https://github.com/UT-Computational-NE/CoreForge.git
        cd CoreForge
        python -m pip install .

    - name: Install and Test Progression Problems
      run: |
        source $(conda info --base)/etc/profile.d/conda.sh && conda activate openmc-env
        pytest test/unit/
        python -m pylint ./progression_problems
